name: 'Automated quick-and-dirty build'
on: [push]
jobs:
  quick-and-dirty-build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
      - name: 'Build'
        uses: jeltsch/actions-isabelle-build@master
        with:
          session-name: Equivalence_Reasoner
          chapter-name: IOG
          source-path: src
          isabelle-version: 2022
          github-sessions: ''
